routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();


// Authentication Routes...
Route::get('admin-login', 'admin\Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('admin-login', 'admin\Auth\LoginController@login');





Route::group(['namespace' => 'admin',  'middleware' => 'auth:admin'],function(){

    Route::get('admin/home','HomeController@index')->name('admin.home');


});


Auth::routes();

Route::get('/home','HomeController@index')->name('home');
Route::resource('admin/user','UserController');
Route::resource('admin/mover','MoverController');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php
namespace App\Http\Controllers;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MoverController.php
<?php

namespace App\Http\Controllers;
use App\Model\admin\mover;

use Illuminate\Http\Request;


class MoverController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
     $movers = mover::all();
     return view('admin.home', compact('movers'));
       // return mover::pluck('id');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //return 'hi';
        $mover = new mover;
        $this->validate($request,[
            'title'=>'required|unique:movers',
            'body'=>'required|unique:movers',
        ]);
        $mover->title = $request->title;
        $mover->body = $request->body;
        $mover->save();
        return redirect('admin/mover');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = mover::find($id);
        return view('admin.show', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = mover::find($id);
        return view('admin.edit', compact('item'));

     //  return 'hi';
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $mover = mover::find($id);
        $this->validate($request,[
            'title'=>'required',
            'body'=>'required',
        ]);
        $mover->title = $request->title;
        $mover->body = $request->body;
        $mover->save();
        session()->flash('messege', 'Updated Successfully');
        return redirect('admin/mover');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $mover = mover::find($id);
        $mover->delete();
        session()->flash('messege', 'Deleted Successfully');
        return redirect('admin/mover');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Model\admin\admin;
use App\Model\user\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        $admins = admin::all();
        return view('admin.user.show',compact('admins','users'));

     //return $users;
    }





    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
}

app/Http/Controllers/admin/HomeController.php
<?php

namespace App\Http\Controllers\admin;
use App\Model\user\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    public function index()
    {
        $users = User::all();
        return view('admin.home',compact('users'));

        //return $users;
    }
}

resources/views/admin/backlogin.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">

                    <div class="card-header text-center">Admin {{ __('Login') }}</div>

                    <div class="card-body">


                         @include('admin.includes.messages')


                        {{--  <form method="POST" action="{{ route('login') }}">
                              {{csrf_field()}}

                              <form>
                                  <fieldset>
                                      <legend>Legend</legend>

                                      <div class="form-group">
                                          <label for="exampleInputEmail1">Email address</label>
                                          <input type="email" class="form-control" name="email" placeholder="Enter email">
                                             </div>
                                      <div class="form-group">
                                          <label for="exampleInputPassword1">Password</label>
                                          <input type="password" class="form-control" name="password" placeholder="Password">
                                      </div>
                                      </fieldset>
                                      <button type="submit" class="btn btn-primary">Submit</button>
                                  </fieldset>
                              </form>


                          </form>--}}
                        <form method="POST" action="{{ route('admin.login') }}" aria-label="{{ __('Login') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="email" class="col-sm-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" name="email" value="{{ old('email') }}" required>

                                    @if ($errors->has('email'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control{{ $errors->has('password') ? ' is-invalid' : '' }}" name="password" required>

                                    @if ($errors->has('password'))
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-6 offset-md-4">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember" {{ old('remember') ? 'checked' : '' }}> {{ __('Remember Me') }}
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Login') }}
                                    </button>

                                    <a class="btn btn-link" href="{{ route('password.request') }}">
                                        {{ __('Forgot Your Password?') }}
                                    </a>
                                </div>
                            </div>
                        </form>


                    </div>

                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/edit.blade.php
@extends('admin.create')
@section('editId', $item->id)
@section('editTitle', $item->title)
@section('editBody', $item->body)
@section('editMethod')
    {{method_field('PUT')}}
@endsection

resources/views/admin/includes/messages.blade.php
@if (count($errors) > 0)
    @foreach ($errors->all() as $error)
        <p class="alert alert-danger">{{ $error }}</p>
    @endforeach
@endif

@if (session()->has('message'))
    <p class="alert alert-success">{{ session('message') }}</p>
@endif

resources/views/admin/layouts/footer.blade.php
<div class="container">
    <div class="footer">
        <p class="text-center">&copy;2015 Copyright Supr.admin. All right reserved !!!</p>
    </div>
</div>
<!-- Javascripts -->
<!-- Load pace first -->
<script src="{{asset('admin/html/plugins/core/pace/pace.min.js')}}"></script>
<!-- Important javascript libs(put in all pages) -->
<script src="{{asset('admin/html/js/libs/jquery-2.1.1.min.js')}}"></script>
<script>
    window.jQuery || document.write('<script src="{{asset('admin/html/js/libs/jquery-2.1.1.min.js')}}">\x3C/script>')
</script>
<script src="{{asset('admin/html/js/libs/jquery-ui-1.10.4.min.js')}}"></script>
<script>
    window.jQuery || document.write('<script src="{{asset('admin/html/js/libs/jquery-ui-1.10.4.min.js')}}">\x3C/script>')
</script>
<script src="{{asset('admin/html/js/libs/jquery-migrate-1.2.1.min.js')}}"></script>
<script>
    window.jQuery || document.write('<script src="{{asset('admin/html/js/libs/jquery-migrate-1.2.1.min.js')}}">\x3C/script>')
</script>
<!--[if lt IE 9]>
<script type="text/javascript" src="{{asset('admin/html/js/libs/excanvas.min.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/html/html5shim.googlecode.com/svn/trunk/html5.js')}}"></script>
<script type="text/javascript" src="{{asset('admin/html/js/libs/respond.min.js')}}"></script>
<![endif]-->
<!-- Bootstrap plugins -->
<script src="{{asset('admin/html/js/bootstrap/bootstrap.js')}}"></script>
<!-- Core plugins ( not remove ) -->
<script src="{{asset('admin/html/js/libs/modernizr.custom.js')}}"></script>
<!-- Handle responsive view functions -->
<script src="{{asset('admin/html/js/jRespond.min.js')}}"></script>
<!-- Custom scroll for sidebars,tables and etc. -->
<script src="{{asset('admin/html/plugins/core/slimscroll/jquery.slimscroll.min.js')}}"></script>
<script src="{{asset('admin/html/plugins/core/slimscroll/jquery.slimscroll.horizontal.min.js')}}"></script>
<!-- Remove click delay in touch -->
<script src="{{asset('admin/html/plugins/core/fastclick/fastclick.js')}}"></script>
<!-- Increase jquery animation speed -->
<script src="{{asset('admin/html/plugins/core/velocity/jquery.velocity.min.js')}}"></script>
<!-- Quick search plugin (fast search for many widgets) -->
<script src="{{asset('admin/html/plugins/core/quicksearch/jquery.quicksearch.js')}}"></script>
<!-- Bootbox fast bootstrap modals -->
<script src="{{asset('admin/html/plugins/ui/bootbox/bootbox.js')}}"></script>
<!-- Other plugins ( load only nessesary plugins for every page) -->
<script src="{{asset('admin/html/plugins/charts/sparklines/jquery.sparkline.js')}}"></script>
<script src="{{asset('admin/html/plugins/charts/knob/jquery.knob.js')}}"></script>
<script src="{{asset('admin/html/plugins/charts/flot/jquery.flot.custom.js')}}"></script>
<script src="{{asset('admin/html/plugins/charts/flot/jquery.flot.pie.js')}}"></script>
<script src="{{asset('admin/html/plugins/charts/flot/jquery.flot.resize.js')}}"></script>
<script src="{{asset('admin/html/plugins/charts/flot/jquery.flot.time.js')}}"></script>
<script src="{{asset('admin/html/plugins/charts/flot/jquery.flot.growraf.js')}}"></script>
<script src="{{asset('admin/html/plugins/charts/flot/jquery.flot.categories.js')}}"></script>
<script src="{{asset('admin/html/plugins/charts/flot/jquery.flot.stack.js')}}"></script>
<script src="{{asset('admin/html/plugins/charts/flot/jquery.flot.orderBars.js')}}"></script>
<script src="{{asset('admin/html/plugins/charts/flot/jquery.flot.tooltip.min.js')}}"></script>
<script src="{{asset('admin/html/plugins/ui/waypoint/waypoints.js')}}"></script>
<script src="{{asset('admin/html/plugins/forms/autosize/jquery.autosize.js')}}"></script>
<script src="{{asset('admin/html/js/jquery.supr.js')}}"></script>
<script src="{{asset('admin/html/js/main.js')}}"></script>
<script src="{{asset('admin/html/js/pages/dashboard.js')}}"></script>


<!-- Javascripts -->

@section('loginfooter')
    @show

resources/views/admin/layouts/head.blade.php
<meta charset="utf-8">
<title>@yield('title', 'Dashboard') | Supr Admin Template</title>
<!-- Mobile specific metas -->
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<!-- Force IE9 to render in normal mode -->
<!--[if IE]><meta http-equiv="x-ua-compatible" content="IE=9" /><![endif]-->
<meta name="author" content="" />
<meta name="description" content="" />
<meta name="keywords" content="" />
<meta name="application-name" content="" />
<!-- Import google fonts - Heading first/ text second -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet" type="text/css">
<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">
<!-- Css files -->
<!-- Icons -->
<link href="{{asset('admin/html/css/icons.css')}}" rel="stylesheet" />
<!-- Bootstrap stylesheets (included template modifications) -->
<link href="{{asset('admin/html/css/bootstrap.css')}}" rel="stylesheet" />
<!-- Plugins stylesheets (all plugin custom css) -->
<link href="{{asset('admin/html/css/plugins.css')}}" rel="stylesheet" />
<!-- Main stylesheets (template main css file) -->
<link href="{{asset('admin/html/css/main.css')}}" rel="stylesheet" />
<!-- Custom stylesheets ( Put your own changes here ) -->
<link href="{{asset('admin/html/css/custom.css')}}" rel="stylesheet" />
<!-- Fav and touch icons -->
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="{{asset('admin/html/img/ico/apple-touch-icon-144-precomposed.png')}}">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="{{asset('admin/html/img/ico/apple-touch-icon-114-precomposed.png')}}">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="{{asset('admin/html/img/ico/apple-touch-icon-72-precomposed.png')}}">
<link rel="apple-touch-icon-precomposed" href="{{asset('admin/html/')}}img/ico/apple-touch-icon-57-precomposed.png">
<link rel="icon" href="{{asset('admin/html/img/ico/favicon.ico')}}" type="image/png">
<!-- Windows8 touch icon ( http://www.buildmypinnedsite.com/ )-->
<meta name="msapplication-TileColor" content="#3399cc" />

resources/views/admin/show.blade.php
@extends('admin.layouts.app')
@section('title', 'Inside mover')
@section('goBody')
    <br>
    <h5 class="text-center text-info">Inside mover table through id</h5>
    <hr>
    <div class="container">

        <div class="row">

            <div class="col-md-4 offset-md-4">
                <div class="list-group">
                    <a href="#" class="list-group-item">
                        <div class="d-flex w-100">
                            <h5 class="mb-1">{{$item->title}}</h5>
                            {{--<small></small>--}}
                        </div>
                        <p class="mb-1">{{$item->body}}</p>
                        <small>{{$item->created_at->diffforHumans()}}</small>
                    </a>

                </div>
            </div>

        </div>


    </div>
@endsection

resources/views/admin/user/show.blade.php
<!doctype html>
<html lang="en">
<head>
    @include('admin.layouts.head')
</head>
<body>
@include('admin.layouts.header')
<div id="wrapper">

@include('admin.layouts.sidebar')
<!-- End #right-sidebar -->

    <!--Body content-->

    <div id="content" class="page-content clearfix">
        <div class="contentwrapper">
            <!--Content wrapper-->
            <div class="heading">
                <!--  .heading-->
                <h3>Data tables</h3>
                <div class="resBtnSearch">
                    <a href="#"><span class="s16 icomoon-icon-search-3"></span></a>
                </div>
                <div class="search">
                    <!-- .search -->
                    <form id="searchform" class="form-horizontal" action="search.html">
                        <input type="text" class="top-search from-control" placeholder="Search here ..."/>
                        <input type="submit" class="search-btn" value=""/>
                    </form>
                </div>
                <!--  /search -->
                <ul class="breadcrumb">
                    <li>You are here:</li>
                    <li>
                        <a href="#" class="tip" title="back to dashboard">
                            <i class="s16 icomoon-icon-screen-2"></i>
                        </a>
                        <span class="divider">
                <i class="s16 icomoon-icon-arrow-right-3"></i>
            </span>
                    </li>
                    <li class="active">Blank Page</li>
                </ul>
            </div>
            <!-- End  / heading-->
            <!-- Start .row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- col-lg-12 start here -->
                    <div class="panel panel-default toggle panelMove panelClose panelRefresh">
                        <!-- Start .panel -->
                        <div class="panel-heading">
                            <h4 class="panel-title">Basic Data tables</h4>
                        </div>
                        <div class="panel-body">
                            <table id="basic-datatables" class="table table-striped table-bordered" cellspacing="0"
                                   width="100%">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach ($admins as $admin)
                                    <tr>
                                        <td>#{{ $loop->index + 1 }}</td>
                                        <td>{{ $admin->name }}</td>
                                        <td>{{ $admin->email }}</td>

                                    </tr>

                                @endforeach

                                </tbody>

                            </table>
                            <a name="" id="" class="btn btn-info" href="#"
                               role="button"><i aria-hidden="true" class="icomoon-icon-user-plus-2"></i>Add User</a>
                        </div>
                    </div>
                    <!-- End .panel -->
                </div>
                <!-- col-lg-12 end here -->


            </div>
            {{--<div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">Users</h3>
                            <a class='col-lg-offset-5 btn btn-success' href="{{ route('user.create') }}">Add New</a>
                            @include('includes.messages')
                            <div class="box-tools pull-right">
                                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                                    <i class="fa fa-minus"></i></button>
                                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                                    <i class="fa fa-times"></i></button>
                            </div>
                        </div>
                        <div class="box-body">
                            <div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Data Table With Full Features</h3>
                                </div>
                                <!-- /.box-header -->
                                <div class="box-body">
                                    <table id="example1" class="table table-bordered table-striped">
                                        <thead>
                                        <tr>
                                            <th>S.No</th>
                                            <th>User Name</th>
                                            <th>Assigned Roles</th>
                                            <th>Status</th>
                                            <th>Edit</th>
                                            <th>Delete</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($users as $user)
                                            <tr>
                                                <td>{{ $loop->index + 1 }}</td>
                                                <td>{{ $user->name }}</td>
                                                <td>
                                                    @foreach ($user->roles as $role)
                                                        {{ $role->name }},
                                                    @endforeach
                                                </td>
                                                <td>{{ $user->status? 'Active' : 'Not Active' }}</td>
                                                <td><a href="{{ route('user.edit',$user->id) }}"><span class="glyphicon glyphicon-edit"></span></a></td>
                                                <td>
                                                    <form id="delete-form-{{ $user->id }}" method="post" action="{{ route('user.destroy',$user->id) }}" style="display: none">
                                                        {{ csrf_field() }}
                                                        {{ method_field('DELETE') }}
                                                    </form>
                                                    <a href="" onclick="
                                                            if(confirm('Are you sure, You Want to delete this?'))
                                                            {
                                                            event.preventDefault();
                                                            document.getElementById('delete-form-{{ $user->id }}').submit();
                                                            }
                                                            else{
                                                            event.preventDefault();
                                                            }" ><span class="glyphicon glyphicon-trash"></span></a>
                                                </td>
                                            </tr>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                        <tfoot>
                                        <tr>
                                            <th>S.No</th>
                                            <th>User Name</th>
                                            <th>Assigned Roles</th>
                                            <th>Status</th>
                                            <th>Edit</th>
                                            <th>Delete</th>
                                        </tr>
                                        </tfoot>
                                    </table>
                                </div>
                                <!-- /.box-body -->
                            </div>
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            Footer
                        </div>
                        <!-- /.box-footer-->
                    </div>
                </div>
            </div>--}}

        <!--Content wrapper-->
            <div class="heading">
                <!--  .heading-->
                <h3>Data tables</h3>
                <div class="resBtnSearch">
                    <a href="#"><span class="s16 icomoon-icon-search-3"></span></a>
                </div>
                <div class="search">
                    <!-- .search -->
                    <form id="searchform" class="form-horizontal" action="search.html">
                        <input type="text" class="top-search from-control" placeholder="Search here ..."/>
                        <input type="submit" class="search-btn" value=""/>
                    </form>
                </div>
                <!--  /search -->
                <ul class="breadcrumb">
                    <li>You are here:</li>
                    <li>
                        <a href="#" class="tip" title="back to dashboard">
                            <i class="s16 icomoon-icon-screen-2"></i>
                        </a>
                        <span class="divider">
                <i class="s16 icomoon-icon-arrow-right-3"></i>
            </span>
                    </li>
                    <li class="active">Blank Page</li>
                </ul>
            </div>
            <!-- End  / heading-->
            <!-- Start .row -->
            <div class="row">
                <div class="col-lg-12">
                    <!-- col-lg-12 start here -->
                    <div class="panel panel-default toggle panelMove panelClose panelRefresh">
                        <!-- Start .panel -->
                        <div class="panel-heading">
                            <h4 class="panel-title">Basic Data tables</h4>
                        </div>
                        <div class="panel-body">
                            <table id="basic-datatables" class="table table-striped table-bordered" cellspacing="0"
                                   width="100%">
                                <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                </tr>
                                </thead>
                                @foreach ($users as $user)
                                    <tr>
                                        <td>#{{ $loop->index + 1 }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>

                                    </tr>

                                @endforeach
                                <tbody>

                                </tbody>

                            </table>
                            <a name="" id="" class="btn btn-info" href="#"
                               role="button"><i aria-hidden="true" class="icomoon-icon-user-plus-2"></i>Add User</a>
                        </div>
                    </div>
                    <!-- End .panel -->
                </div>
                <!-- col-lg-12 end here -->


            </div>
            <!-- End .row -->
        </div>
        <!-- End contentwrapper -->
    </div>

    <!--Body content-->
    @include('admin.layouts.footer')
</div>
</body>
</html>